In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
def get_csv(csv_file, enconding_value):
    df = pd.read_csv(csv_file, encoding = enconding_value, na_values=["-", False])
    return df

superheroes = get_csv("superheroes.csv", "latin-1")
superheroes_powers= get_csv("superheroespowers.csv", "latin-1")

----------SUPERHEROES INFO---------------

In [3]:
superheroes.head()

,Unnamed: 0,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,NaN,A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,NaN,good,441.0
1,1.0,Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
2,2.0,Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0
3,3.0,Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,NaN,bad,441.0
4,4.0,Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,NaN,bad,-99.0

In [4]:
def rename_column(df, old_column, new_column):
    return df.rename(columns = {old_column: new_column}, inplace = True)

superherores = rename_column(superheroes, "name", "Name")

superheroes.head()

,Unnamed: 0,Name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,NaN,A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,NaN,good,441.0
1,1.0,Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
2,2.0,Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0
3,3.0,Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,NaN,bad,441.0
4,4.0,Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,NaN,bad,-99.0

In [5]:
def capitalize_column_values(df, column):
    df[column] = df[column].str.capitalize()

capitalize_column_values(superheroes, "Alignment")
capitalize_column_values(superheroes, "Eye color")
capitalize_column_values(superheroes, "Skin color")

superheroes.head()

,Unnamed: 0,Name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,NaN,A-Bomb,Male,Yellow,Human,No Hair,203.0,Marvel Comics,NaN,Good,441.0
1,1.0,Abe Sapien,Male,Blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,Blue,Good,65.0
2,2.0,Abin Sur,Male,Blue,Ungaran,No Hair,185.0,DC Comics,Red,Good,90.0
3,3.0,Abomination,Male,Green,Human / Radiation,No Hair,203.0,Marvel Comics,NaN,Bad,441.0
4,4.0,Abraxas,Male,Blue,Cosmic Entity,Black,-99.0,Marvel Comics,NaN,Bad,-99.0

In [6]:
def pounds_to_kilograms(df, column):
      for value in df[column]:
            df[column] = df[column].apply(lambda value: value/2.205 if value > 0 else None)
            
pounds_to_kilograms(superheroes, "Weight")

superheroes.head()

,Unnamed: 0,Name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,NaN,A-Bomb,Male,Yellow,Human,No Hair,203.0,Marvel Comics,NaN,Good,3.824113e-250
1,1.0,Abe Sapien,Male,Blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,Blue,Good,5.636448e-251
2,2.0,Abin Sur,Male,Blue,Ungaran,No Hair,185.0,DC Comics,Red,Good,7.804313e-251
3,3.0,Abomination,Male,Green,Human / Radiation,No Hair,203.0,Marvel Comics,NaN,Bad,3.824113e-250
4,4.0,Abraxas,Male,Blue,Cosmic Entity,Black,-99.0,Marvel Comics,NaN,Bad,NaN

In [7]:
def feet_to_meters(df, column):
    df[column] = df[column].apply(lambda value: value/3.281 if value > 0 else None)
            
feet_to_meters(superheroes, "Height")

superheroes.head()

,Unnamed: 0,Name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,NaN,A-Bomb,Male,Yellow,Human,No Hair,61.871381,Marvel Comics,NaN,Good,3.824113e-250
1,1.0,Abe Sapien,Male,Blue,Icthyo Sapien,No Hair,58.213959,Dark Horse Comics,Blue,Good,5.636448e-251
2,2.0,Abin Sur,Male,Blue,Ungaran,No Hair,56.385248,DC Comics,Red,Good,7.804313e-251
3,3.0,Abomination,Male,Green,Human / Radiation,No Hair,61.871381,Marvel Comics,NaN,Bad,3.824113e-250
4,4.0,Abraxas,Male,Blue,Cosmic Entity,Black,NaN,Marvel Comics,NaN,Bad,NaN

In [8]:
def rename_column(df, old_column, new_column):
    return df.rename(columns = {old_column: new_column}, inplace = True)

superherores = rename_column(superheroes, "Height", "Height (m)")
superherores = rename_column(superheroes, "Weight", "Weight (kg)")

superheroes.head()

,Unnamed: 0,Name,Gender,Eye color,Race,Hair color,Height (m),Publisher,Skin color,Alignment,Weight (kg)
0,NaN,A-Bomb,Male,Yellow,Human,No Hair,61.871381,Marvel Comics,NaN,Good,3.824113e-250
1,1.0,Abe Sapien,Male,Blue,Icthyo Sapien,No Hair,58.213959,Dark Horse Comics,Blue,Good,5.636448e-251
2,2.0,Abin Sur,Male,Blue,Ungaran,No Hair,56.385248,DC Comics,Red,Good,7.804313e-251
3,3.0,Abomination,Male,Green,Human / Radiation,No Hair,61.871381,Marvel Comics,NaN,Bad,3.824113e-250
4,4.0,Abraxas,Male,Blue,Cosmic Entity,Black,NaN,Marvel Comics,NaN,Bad,NaN

In [9]:
def change_columns_order(df, list_new_columns_order):
    return df[list_new_columns_order]

superheroes = change_columns_order(superheroes, ["Name", "Race", "Gender", "Height (m)", "Weight (kg)", "Skin color", "Hair color", "Eye color", "Alignment", "Publisher"])

superheroes.head()

,Name,Race,Gender,Height (m),Weight (kg),Skin color,Hair color,Eye color,Alignment,Publisher
0,A-Bomb,Human,Male,61.871381,3.824113e-250,NaN,No Hair,Yellow,Good,Marvel Comics
1,Abe Sapien,Icthyo Sapien,Male,58.213959,5.636448e-251,Blue,No Hair,Blue,Good,Dark Horse Comics
2,Abin Sur,Ungaran,Male,56.385248,7.804313e-251,Red,No Hair,Blue,Good,DC Comics
3,Abomination,Human / Radiation,Male,61.871381,3.824113e-250,NaN,No Hair,Green,Bad,Marvel Comics
4,Abraxas,Cosmic Entity,Male,NaN,NaN,NaN,Black,Blue,Bad,Marvel Comics

In [10]:
def total_nulls(df):
    return df.isnull().sum()
    
total_nulls(superheroes)

Name             0
Race           304
Gender          29
Height (m)     217
Weight (kg)    239
Skin color     662
Hair color     172
Eye color      172
Alignment        7
Publisher       15
dtype: int64

In [11]:
def delete_unuseful_columns(df, percentage): #Detele columns with "100% - percentage" null values
    for column in df:
        if df[column].isnull().sum() > len(df.index)*percentage/100:
            del df[column]

delete_unuseful_columns(superheroes, 50)
    
superheroes.head()

,Name,Race,Gender,Height (m),Weight (kg),Hair color,Eye color,Alignment,Publisher
0,A-Bomb,Human,Male,61.871381,3.824113e-250,No Hair,Yellow,Good,Marvel Comics
1,Abe Sapien,Icthyo Sapien,Male,58.213959,5.636448e-251,No Hair,Blue,Good,Dark Horse Comics
2,Abin Sur,Ungaran,Male,56.385248,7.804313e-251,No Hair,Blue,Good,DC Comics
3,Abomination,Human / Radiation,Male,61.871381,3.824113e-250,No Hair,Green,Bad,Marvel Comics
4,Abraxas,Cosmic Entity,Male,NaN,NaN,Black,Blue,Bad,Marvel Comics

In [12]:
def rename_nulls(df): #Replace NaN with "-"
    df.fillna("-", inplace=True)
    
rename_nulls(superheroes)

superheroes.head()

,Name,Race,Gender,Height (m),Weight (kg),Hair color,Eye color,Alignment,Publisher
0,A-Bomb,Human,Male,61.8714,3.82411e-250,No Hair,Yellow,Good,Marvel Comics
1,Abe Sapien,Icthyo Sapien,Male,58.214,5.63645e-251,No Hair,Blue,Good,Dark Horse Comics
2,Abin Sur,Ungaran,Male,56.3852,7.80431e-251,No Hair,Blue,Good,DC Comics
3,Abomination,Human / Radiation,Male,61.8714,3.82411e-250,No Hair,Green,Bad,Marvel Comics
4,Abraxas,Cosmic Entity,Male,-,-,Black,Blue,Bad,Marvel Comics

----------SUPERHEROES POWERS---------------

In [13]:
superheroes_powers.head()

,hero_names,Agility,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Durability,Stealth,Energy Absorption,Flight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,3-D Man,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A-Bomb,NaN,True,NaN,NaN,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abe Sapien,True,True,NaN,NaN,True,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abin Sur,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abomination,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
def rename_column(df, old_column, new_column):
    return df.rename(columns = {old_column: new_column}, inplace = True)

superherores_powers = rename_column(superheroes_powers, "hero_names", "Name")

superheroes_powers.head()

,Name,Agility,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Durability,Stealth,Energy Absorption,Flight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,3-D Man,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A-Bomb,NaN,True,NaN,NaN,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abe Sapien,True,True,NaN,NaN,True,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abin Sur,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abomination,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
def rename_trues_and_falses(df): #Replace False with "-" and True with "X"
    df.replace(to_replace = {False: None, True: "X"}, inplace = True)

rename_trues_and_falses(superheroes_powers)

superheroes_powers.head()

,Name,Agility,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Durability,Stealth,Energy Absorption,Flight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,3-D Man,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A-Bomb,NaN,X,NaN,NaN,NaN,X,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abe Sapien,X,X,NaN,NaN,X,X,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abin Sur,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abomination,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
def total_nulls(df):
    return df.isnull().sum()
    
total_nulls(superheroes_powers)

Name                       0
Agility                  425
Accelerated Healing      489
Lantern Power Ring       656
Dimensional Awareness    642
Cold Resistance          620
Durability               410
Stealth                  541
Energy Absorption        590
Flight                   455
Danger Sense             637
Underwater breathing     646
Marksmanship             548
Weapons Master           562
Power Augmentation       659
Animal Attributes        642
Longevity                554
Intelligence             509
Super Strength           307
Cryokinesis              648
Telepathy                575
Energy Armor             659
Energy Blasts            520
Duplication              651
Size Changing            612
Density Control          652
Stamina                  378
Astral Travel            663
Audio Control            660
Dexterity                661
                        ...
Intuitive aptitude       666
Vision - Microscopic     648
Melting                  665
Wind Control             664
Super Breath             644
Wallcrawling             633
Vision - Night           633
Vision - Infrared        645
Grim Reaping             664
Matter Absorption        656
The Force                661
Resurrection             652
Terrakinesis             665
Vision - Heat            648
Vitakinesis              665
Radar Sense              661
Qwardian Power Ring      665
Weather Control          659
Vision - X-Ray           644
Vision - Thermal         644
Web Creation             653
Reality Warping          651
Odin Force               665
Symbiote Costume         658
Speed Force              666
Phoenix Force            666
Molecular Dissipation    666
Vision - Cryo            665
Omnipresent              665
Omniscient               665
Length: 168, dtype: int64

In [17]:
def delete_unuseful_columns(df, percentage): #Detele columns with "100% - percentage" null values
    for column in df:
        if df[column].isnull().sum() > len(df.index)*percentage/100:
            del df[column]

delete_unuseful_columns(superheroes_powers, 75)
    
superheroes_powers.head()

,Name,Agility,Accelerated Healing,Durability,Flight,Super Strength,Stamina,Super Speed
0,3-D Man,X,NaN,NaN,NaN,X,X,X
1,A-Bomb,NaN,X,X,NaN,X,X,NaN
2,Abe Sapien,X,X,X,NaN,X,X,NaN
3,Abin Sur,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abomination,NaN,X,NaN,NaN,X,X,X

In [18]:
def rename_nulls(df): #Replace NaN with "-"
    df.fillna("-", inplace=True)
    
rename_nulls(superheroes_powers)

superheroes_powers.head()

,Name,Agility,Accelerated Healing,Durability,Flight,Super Strength,Stamina,Super Speed
0,3-D Man,X,-,-,-,X,X,X
1,A-Bomb,-,X,X,-,X,X,-
2,Abe Sapien,X,X,X,-,X,X,-
3,Abin Sur,-,-,-,-,-,-,-
4,Abomination,-,X,-,-,X,X,X

----------SUPERHEROES FULL DATA---------------

In [19]:
#Merge superheroes + superheroes_powers:
superheroes_full_data = pd.merge(superheroes, superheroes_powers, on='Name')
superheroes_full_data.head()

,Name,Race,Gender,Height (m),Weight (kg),Hair color,Eye color,Alignment,Publisher,Agility,Accelerated Healing,Durability,Flight,Super Strength,Stamina,Super Speed
0,A-Bomb,Human,Male,61.8714,3.82411e-250,No Hair,Yellow,Good,Marvel Comics,-,X,X,-,X,X,-
1,Abe Sapien,Icthyo Sapien,Male,58.214,5.63645e-251,No Hair,Blue,Good,Dark Horse Comics,X,X,X,-,X,X,-
2,Abin Sur,Ungaran,Male,56.3852,7.80431e-251,No Hair,Blue,Good,DC Comics,-,-,-,-,-,-,-
3,Abomination,Human / Radiation,Male,61.8714,3.82411e-250,No Hair,Green,Bad,Marvel Comics,-,X,-,-,X,X,X
4,Abraxas,Cosmic Entity,Male,-,-,Black,Blue,Bad,Marvel Comics,-,-,-,X,X,-,X

----------ANALYSIS---------------

In [20]:
superheroes_full_data[superheroes_full_data.Gender == "-"]

,Name,Race,Gender,Height (m),Weight (kg),Hair color,Eye color,Alignment,Publisher,Agility,Accelerated Healing,Durability,Flight,Super Strength,Stamina,Super Speed
81,Bird-Brain,-,-,-,-,-,-,Good,Marvel Comics,-,-,-,X,-,-,-
121,Box IV,-,-,-,-,Brown / Black,Brown,Good,Marvel Comics,-,-,-,-,-,-,-
146,Captain Universe,God / Eternal,-,-,-,-,-,Good,Marvel Comics,-,-,-,X,-,-,-
210,Ego,-,-,-,-,-,-,Bad,Marvel Comics,-,-,-,-,X,-,X
224,Fabian Cortez,-,-,59.7379,8.3246e-251,Brown,Blue,Bad,Marvel Comics,-,-,-,-,-,-,-
228,Feral,-,-,53.3374,4.33573e-251,Orange / White,Yellow (without irises),Good,Marvel Comics,X,X,-,-,X,-,X
232,Firelord,-,-,58.8235,8.58474e-251,Yellow,White,Good,Marvel Comics,-,-,X,X,-,-,-
241,Forge,-,-,55.7757,7.02388e-251,Black,Brown,Good,Marvel Comics,-,-,-,-,-,-,-
253,Ghost Rider II,-,-,-,-,-,-,Good,Marvel Comics,-,-,X,-,X,-,-
257,Godzilla,Kaiju,-,32.9168,-,-,-,Bad,-,X,-,X,-,X,X,-
365,Living Brain,-,-,60.3475,3.12173e-250,-,Yellow,Bad,Marvel Comics,-,-,X,X,X,-,-
366,Living Tribunal,Cosmic Entity,-,-,-,No Hair,Blue,Neutral,Marvel Comics,X,X,-,X,X,-,X
378,Machine Man,-,-,55.7757,3.32117e-250,Black,Red,Good,Marvel Comics,-,-,X,X,X,X,-
382,Man of Miracles,God / Eternal,-,-,-,Silver,Blue,-,Image Comics,-,X,-,-,X,-,X
452,One-Above-All,Cosmic Entity,-,-,-,-,-,Neutral,Marvel Comics,X,X,X,X,X,-,X
458,Parademon,Parademon,-,-,-,-,-,Bad,DC Comics,-,-,-,X,X,-,-
528,Shadow King,-,-,56.3852,1.29205e-250,-,Red,Good,Marvel Comics,-,-,-,-,-,-,-
562,Spider-Man,Human,-,54.2518,6.67702e-251,Brown,Red,Good,Marvel Comics,X,X,X,-,X,X,X

In [21]:
superheroes_full_data.loc[562]

Name                      Spider-Man
Race                           Human
Gender                             -
Height (m)                   54.2518
Weight (kg)             6.67702e-251
Hair color                     Brown
Eye color                        Red
Alignment                       Good
Publisher              Marvel Comics
Agility                            X
Accelerated Healing                X
Durability                         X
Flight                             -
Super Strength                     X
Stamina                            X
Super Speed                        X
Name: 562, dtype: object